// exports.catchAsync = (func) => {
//   try {
//     func(res, req, next);
//   } catch (error) {
//     console.log(error);
//   }
// };
